### ISSUE TITLE
[FR] Breadcrumbs-like parent-child and siblings connections

### ISSUE THREAD

**Issue by zanodor** [aarongilly/obsidian-semantic-canvas-plugin#2]
Hi there

I am not a big canvas user but I gave your plugin a shot. It has a lot of potential. 

I am more interested in the canvas generating feature. It would be interesting to use it as a mermaid or plantUML chart substitute.

Currently, the single group property is lacking.

I am thinking of a Breadcrumbs-like (see also ExcaliBrain) functionality here, with related topics, parent topics, and up/down functionality. Even the Linked Data Vocabularies generated properties could be used. The question is, how deep...

So obviously this has a lot of questions and future potential. 

Cheers

**Comment by aarongilly** [comment]
yeah this was something I started off with the intention to do - full blown semantics and ontology building, with reasoners and whatnot. Ultimately I decided to keep the plugin very *simple* because I don't have nearly the resources necessary to build out all that functionality. The implementation was designed to provide some handy utilities without introducing a bunch of edge cases. 

I agree that this would be sweet, but for now that's a "probably never" feature.
